[QNN EP] Add support to build ARM64 (ARM64x) Zip (#397)

diff --git a/.github/workflows/qualcomm-internal-release.yml b/.github/workflows/qualcomm-internal-release.yml
--- a/.github/workflows/qualcomm-internal-release.yml
+++ b/.github/workflows/qualcomm-internal-release.yml
@@ -268,6 +268,11 @@ jobs:
         with:
           name: windows-arm64-py3.11-zip
 
+      - name: Download ARM64 (ARM64x) Windows Zip Package
+        uses: ./.github/actions/download-ci-artifact
+        with:
+          name: windows-arm64x-py3.11-zip
+
       - name: Download aarch64 manylinux_2_34 Linux TGZ Package from Artifactory
         uses: ./.github/actions/download-ci-artifact
         with:
@@ -328,12 +333,12 @@ jobs:
           echo "Found $count .tar.bz2 archive(s)"
           [ "$count" -eq 3 ] || { echo "ERROR: Expected 3 .tar.bz2 archives, found $count"; exit 1; }
 
-      - name: Verify Zip artifact
+      - name: Verify Zip artifacts
         run: |
-          # 4 test archives + 1 windows zip + 3 PDB archives = 8 zips
+          # 4 test archives + 1 Windows ARM64 zip + 1 Windows ARM64 (ARM64x) zip + 3 PDB archives = 9 zips
           count=$(find "${{ github.workspace }}/build" -name "*.zip" | wc -l)
           echo "Found $count Zip archive(s)"
-          [ "$count" -eq 8 ] || { echo "ERROR: Expected 8 Zip archives, found $count"; exit 1; }
+          [ "$count" -eq 9 ] || { echo "ERROR: Expected 9 Zip archives, found $count"; exit 1; }
 
       - name: Verify TGZ artifact
         run: |
diff --git a/.github/workflows/qualcomm-internal-upload-artifactory-from-github.yml b/.github/workflows/qualcomm-internal-upload-artifactory-from-github.yml
--- a/.github/workflows/qualcomm-internal-upload-artifactory-from-github.yml
+++ b/.github/workflows/qualcomm-internal-upload-artifactory-from-github.yml
@@ -336,6 +336,11 @@ jobs:
         with:
           name: windows-arm64-py3.11-zip
 
+      - name: Download Windows ARM64 (ARM64x) Zip from Artifactory
+        uses: ./.github/actions/download-ci-artifact
+        with:
+          name: windows-arm64x-py3.11-zip
+
       - name: Download Linux aarch64 manylinux_2_34 TGZ from Artifactory
         uses: ./.github/actions/download-ci-artifact
         with:
@@ -358,10 +363,10 @@ jobs:
 
       - name: Verify Zip artifacts
         run: |
-          # 1 windows zip + 3 PDB archives = 4 zips
+          # 1 Windows ARM64 Zip + 3 PDB archives + 1 Windows ARM64 (ARM64x) Zip = 5 zips
           count=$(find "${{ github.workspace }}/build" -name "*.zip" | wc -l)
           echo "Found $count Zip archive(s)"
-          [ "$count" -eq 4 ] || { echo "ERROR: Expected 4 Zip archive, found $count"; exit 1; }
+          [ "$count" -eq 5 ] || { echo "ERROR: Expected 5 Zip archive, found $count"; exit 1; }
 
       - name: Verify TGZ artifact
         run: |
@@ -369,10 +374,16 @@ jobs:
           echo "Found $count TGZ archive(s)"
           [ "$count" -eq 1 ] || { echo "ERROR: Expected 1 TGZ archive, found $count"; exit 1; }
 
-      - name: Prepare Windows Zip libs for signing
+      - name: Prepare Windows ARM64 Zip lib for signing
         run: |
           ./qcom/scripts/signing/prepare_zip_for_signing.sh \
             "${{ github.workspace }}/build/windows-arm64/Release/dist" \
+            "${{ github.workspace }}/build/dist/output"
+
+      - name: Prepare Windows ARM64 (ARM64x) Zip lib for signing
+        run: |
+          ./qcom/scripts/signing/prepare_zip_for_signing.sh \
+            "${{ github.workspace }}/build/windows-arm64x/Release/Release/dist" \
             "${{ github.workspace }}/build/dist/output"
 
       - name: Upload unsigned Windows Zip libs to Artifactory
@@ -409,6 +420,11 @@ jobs:
           # Upload Windows ARM64 archive and PDB archive
           ./qcom/scripts/upleveling/upload_zip_to_artifactory.sh \
             "${{ github.workspace }}/build/windows-arm64/Release/dist" \
+            "$NETRC_FILE"
+
+          # Upload Windows ARM64 (ARM64x) archive
+          ./qcom/scripts/upleveling/upload_zip_to_artifactory.sh \
+            "${{ github.workspace }}/build/windows-arm64x/Release/Release/dist" \
             "$NETRC_FILE"
 
           # Upload Linux aarch64 manylinux_2_34 zip
